server:
  port: 7781

# active 基本配置
spring:
  activemq:
    broker-url: tcp://localhost:61617
    user: admin
    password: admin
  jms:
    # 是否采用发布订阅方式
    pub-sub-domain: true # 默认是false false =queue true =Topic

# 自己定义队列名称
myTopic: boot-activemq-topic
